# Generated by Django 4.1 on 2023-01-05 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='服の名前')),
                ('body_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='着丈')),
                ('chest', models.PositiveIntegerField(blank=True, null=True, verbose_name='胸囲')),
                ('shoulder', models.PositiveIntegerField(blank=True, null=True, verbose_name='肩幅')),
                ('arm', models.PositiveIntegerField(blank=True, null=True, verbose_name='袖丈')),
                ('comfort', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='polls.comfort')),
                ('type', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='polls.type')),
            ],
        ),
    ]
