# Generated by Django 4.1 on 2023-01-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_settingsize_comfort_alter_settingsize_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsize',
            name='arm',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='袖丈'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settingsize',
            name='body_length',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='着丈'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settingsize',
            name='chest',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='胸囲'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settingsize',
            name='shoulder',
            field=models.CharField(blank=True, default=1, max_length=150, verbose_name='肩幅'),
            preserve_default=False,
        ),
    ]
