# Generated by Django 4.1 on 2023-01-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_settingsize_arm_alter_settingsize_body_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsize',
            name='arm',
            field=models.PositiveIntegerField(blank=True, max_length=150, verbose_name='袖丈'),
        ),
        migrations.AlterField(
            model_name='settingsize',
            name='body_length',
            field=models.PositiveIntegerField(blank=True, max_length=150, verbose_name='着丈'),
        ),
        migrations.AlterField(
            model_name='settingsize',
            name='chest',
            field=models.PositiveIntegerField(blank=True, max_length=150, verbose_name='胸囲'),
        ),
        migrations.AlterField(
            model_name='settingsize',
            name='shoulder',
            field=models.PositiveIntegerField(blank=True, max_length=150, verbose_name='肩幅'),
        ),
    ]
